---
title: "The Pondering Probabilist"
menu:
    main:
        name: "About"
        weight: 2
        url: "/about/"
        pre: "<i class='fa fa-question-circle'></i>"
        identifier: "about"
output: html_notebook
---

The Pondering Probabilist is my (Matt) attempt to create a blog to organize and disseminate my thoughts on various topics through what I believe to be the most pliable medium available to me: the web. Per the name, much of the content is focused on using probability and statistics, or relatives thereof, to either share interesting insights about my research, or (for the more general public) to understand and reason about the complex topics facing society today. More importantly, the purpose of the content is spark discussions on such topics in an educational way, for all parties involved. 

One of the primary motivations for this blog is to attempt to use of probability and statistics (P&S) properly in such topics; in even the most important discussions in society today, PS is either absent or misrepresented. Most [lawyers consider P&S to be useless](). We need amazing projects such as [the innocence project]() to exist, because of a fundamental misunderstanding of the risk associated with false-positive rates in convictions, and in the misuse of DNA evidence. One need only turn on the news to see the widespread misintepretation of research results, such as the (staged) research study on whether [chocolate increased metabolism, which could help you lose weight](https://io9.gizmodo.com/i-fooled-millions-into-thinking-chocolate-helps-weight-1707251800).

The secondary motivation for this effort is more personal. I've often observed between my politically-oriented colleagues that neither side seems ameneable to conceding discussion points to the other. At best, the discussions are civil, leading to an "agree to disagree" junction, possibly due to _lack of data_ or disagreement on the _bias_ of reported statistics. At worst, the discussions are emotionally-driven, and progress towards mutual understanding seems impossible. Either way, the mobility of most discussions I see staggers, and both sides end leaving even more polorized than when the discussion began. This seems to have also occurred at the national scale between followers of the two primary political parties, [with help from Russian hackers](). 

But discussions don't have to be polarizing, and reasonable conclusions mutually agreed on by everyone can be reached. The tool I choose to use to facilitate this is probability. John Hartigan, a legendary statistician (now-retired) who was far ahead of his time, [once had a interview published](http://www.stat.yale.edu/Conferences/Stats2009/AConversationwithJohnHartigan.pdf) on his thoughts on various topics in probability theory. He was asked:  

> Interviewer: But if somebody disagreed with you about the probability of an event, how would you engage them in argument?

His response was as follows:

> Hartigan: Consider the probability that President Bush will be reelected. I wouldn’t say "it's 0.3 and that's the end of it." I would say it is 0.3 for these reasons and, if he wanted to disagree with me, I would expect him to produce reasons, and I should listen to those reasons and maybe change my probability. That's alright, because probability should depend on knowledge and, in fact, one of the reasons that we engage in argument is to extract knowledge. So I would go through what I regard as all the relevant facts for the possibility of President Bush being reelected and I would try to weight them. Now how you do that exactly is pretty hard I agree. Nevertheless in principle I think that is the way you should go about it. Now this person might come and say, "No it's 0.7 and that's the end of it." (Laughter.) I would say, "No, it's not the end of it. Tell me why," and if he refuses to tell me why, then I regard that as an inadequate argument. I would expect him to say that these are my reasons and I might say, "Yes, I didn't think of that. I will change my probability," and I would expect him to address my reasons, to say, "No, you shouldn’t take any notice of those reasons." I can’t see why there shouldn’t be a reasonable argument about these things.

I think his sentiments highlight an attitude that many people have today. Indeed, there _are_ many people (some who've I had the pleasure of meeting!) who approach heated topics reasonably. Yet, for one reason or another, the complexity of the topic hinders progress, and mobility with respect to changing viewpoints staggers. 

## A solution?

These are issues, however, that can be solved with probability and statistics. Data sets are becoming increasingly available by the day. There are tools for handling [_statistical bias_](https://en.wikipedia.org/wiki/Bias_(statistics)). There are predictive models which have explicitly stated [assumptions](https://en.wikipedia.org/wiki/Inductive_bias), assumptions which can be [empirically tested](https://en.wikipedia.org/wiki/Statistical_hypothesis_testing). It is true that many people encounter mathematical anxiety when it comes to statistics. I think the hypothetical data set described by [SPSS tutorial on factor analysis](https://stats.idre.ucla.edu/spss/seminars/introduction-to-factor-analysis/a-practical-introduction-to-factor-analysis/) sums up the more common reasons. 

But I genuinely believe the field of P&S truly contains the tools and knowledge to address the hindrances to such discussions. I quote Hartigan again in this regard: "statistics is more than just a subset of mathematics." Moreover, I believe that if presented correctly, using P&S can be fascinating and rewarding way to live. 

## Principles
Out of principle, in all of my content posts I endeavour to publish content under the following principles: 

- Use _data_ to back up assertions, when possible, and to make the data widely available.

- Use _probability theory_ to guide my analyses. If there are assumptions associated with a given model, _state them explicitly_, and give a rationale as to why such assumptions are reasonable. 

- Obey the principles of _the scientific method_, e.g. by making all code, data, and analyses _available_ and _reproducible_ (ideally, using _free_ software!). 

- Systematically address concerns of bias, data quality, or conflict(s) of interest _empirically_ 

- Have fun in learning new perspectives



