# pages = [
# 	{ title = "CV", url = "/cv" }, 
# 	{ title = "Projects", url = "/projects"}, 
# 	{ title = "Publications", url = "https://scholar.google.com/citations?hl=en&user=2lPQ3UQAAAAJ"}, 
# 	{ title = "Code", url = "/software" },
# 	{ title = "Blog", url = "/blog"}
# ]

[[pages]]
title = "CV"
url = "/cv"

[[pages]]
title = "Projects"
url = "/projects"

[[pages]]
title = "Publications"
url = "/https://scholar.google.com/citations?hl=en&user=2lPQ3UQAAAAJ"

[[pages]]
title = "Code"
url = "/software"

[[pages]]
title = "Blog"
url = "/blog"