baseurl = "/"   # https://peekxc.github.io/
languageCode = "en-us"
title = "Pondering Centrist Blog"
theme = ""
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = "10" # Number of posts per page

[Author]
    name = "Matt Piekenbrock"
    bio = "Research student."
    avatar = "img/avatar.png"

[Params]
    subtitle = "Pondering the Universe one topic at a time."
    description = "Matt Piekenbrock's Personal blog about everything"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[permalinks]
    post = "/:year-:month-:slug/"
