baseurl: /
languageCode: en-us
title: Pondering Probabilist
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _files$
  - _cache$
paginate: '10'

Author:
  name: Matt Piekenbrock
  bio: Research student.
  avatar: img/avatar.png
wordCount:
  other: "{{ .WordCount }} words"
Params:
  subtitle: Pondering the universe one topic at a time.
  description: Matt Piekenbrock's personal blog about everything
  highlightjsVersion: 9.11.0
  highlightjsCDN: //cdn.bootcss.com
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  widgets:
    search: true                # Enable "Search" widget
    recent_articles: true       # Enable "Recent articles" widget
    recent_articles_num: 10     # Set the number of articles in the "Recent articles" widget
    categories: true            # Enable "Categories" widget
    tags: true                  # Enable "Tags" widget
    tags_counter: true         # Enable counter for each tag in "Tags" widget (disabled by default)
taxonomies:
  category: categories
  tag: tags
permalinks:
  post: '/:year/:month/:title/'						
