---
title: "Drunkard's Walk: Book Review"
date: "2019-09-22"
categories: "markdown"
tags: ["review", "books", "probability", "statistics"]
slug: "drunkards-walk-review"
author: "Matt Piekenbrock"
include_toc: false
output: 
  html_document:
    keep_md: TRUE
    self_contained: TRUE
---

When I began typing this review, I read a number of articles online on "how to give a good book review." 

There were a number of recommendations of the form "...". While some of the advice was indeed good, 
I couldn't help but tinge at the feeling of reading bulletted lists yielding cookbook-type 
advice like "list the main characters. Who were they? What problems did they run into?". I felt 
equally disparate upon thinking that most book reviews on shopping sites (e.g. amazon) reduce 
the nuances of the book down to 10 point rating system visualized as 'stars'. 

Instead, I decided to flee to a stronger medium from which I could properly convey my opinions on the
things I was interested in, namely in movies, programming, books, mathematics, etc. 


The Drunkards Walk - A Review 

The Drunkards Walk is a(nother) phenomenal book straight out of the mind of Leonard Mlodinow. 

Effectively, the book chronologically walks you through history of probability and statistics (P&S) in an 
very informal way by describing the life experiences of the famous scientists and statisticians that 
made major contributions to the field. The goal of the text is to completely diverge from the cookbook 
style of "here's what the expected value of a random variable is and here's what it means" and instead 
present various P&S concepts (like expected value) from the perspective of the person(s) who first 
established the foundation from which the concept arose. 

For example, Pascal's triangle is an important concept contributing to the shape of the normal distribution, 
the .... It is described mathematically as: 

Although Pascal wasn't the first to forumlate the recursive definition of the binomial coefficient in the 
well-known triangular form, he did contribute quite a bit to the use of it. Rather than describing its 
use however, Mlodinow described Pascals life: a skeptic turned devout after the exploring the 
philosophical concept known as Pascals Wager, now often studied in philosophy, english, mathematics, etc courses. 
Pascal was plagued by many afflictions, and was known to ...
After having come to his conclusion on the expected potential gains of the after-life, Pascal took up 
a spiked belt that would routine cinch him as he walked.




